### ISSUE TITLE
No Such Method Error

### ISSUE THREAD

**Issue by power7714** [aerisweather/AerisAndroidSDK#3]
I'm using maps-lib 1.2

> java.lang.NoSuchMethodError: com.google.android.gms.maps.MapView.getMap
>                                                                                        at com.hamweather.aeris.maps.AerisMapView.init(AerisMapView.java:218)

I'm using : compile 'com.google.android.gms:play-services-maps:9.4.0'

using just play-services:9.4.0 produces the error: couldn't find com.google.android.firebase.FirebaseInitProvider  so I don't use that one. I need this working ASAP.

**Comment by sshie** [comment]
Google discontinued support for the getMap() method with the latest version of the Play services. The SDK dev team has an update coming soon that updates this to that the newer getMapAsynch() call. I'm told that any version of Google Maps prior to 9.4.0 still accepts the getMap() call, so the immediate solution is referencing a prior version in your Gradle file. 

The Aeris Demo project uses play services 8.4.0 with the 1.2 version of the maps lib.

dependencies {
compile 'com.google.android.gms:play-services:8.4.0'
compile 'com.hamweather:aeris-maps-library:1.2@aar'
}

I believe the next update for the SDK is scheduled for early quarter 4.
