### ISSUE TITLE
Build failures due to 2.0.0 beta repository url

### ISSUE THREAD

**Issue by wkw** [aerisweather/AerisAndroidSDK#4]
Was trying to bootstrap the demo project for the first time today and ran into two build errors.
see this section: https://github.com/aerisweather/AerisAndroidSDK/blob/3873d8ddbc3a3835c06f0ecb5b53fa6758003bbd/AerisDemo/build.gradle#L2

> `Could not find com.android.tools.build:gradle:2.2.3.`

This was fixed by adding `jcenter()` to the repositories list `buildscript { ... ` setting.

After getting past that, I kept getting:

>`Could not find com.aerisweather:aeris-maps-lib:2.0.0.`

(_should note that android development is fairly new to me so the solution might be more obvious to others and not take an hour of digging..._)

This turned out to be a non-existent repo: [https://oss.sonatype.org/content/repositories/comaerisweather-1025](https://oss.sonatype.org/content/repositories/comaerisweather-1025) which is referenced both on [aeris sdk docs page](http://www.aerisweather.com/support/docs/toolkits/aeris-android-sdk/reference/2.0.0-beta/) and in [build.gradle](https://github.com/aerisweather/AerisAndroidSDK/blob/3873d8ddbc3a3835c06f0ecb5b53fa6758003bbd/AerisDemo/build.gradle#L52) [in two locations].

For anyone else having similar problems, locate latest *available* repos at [https://oss.sonatype.org/#nexus-search;quick~aeris](https://oss.sonatype.org/#nexus-search;quick~aeris). As of this writing, it was `-1050`.

**Comment by sshie** [comment]
Hi Wayne,

Thanks for the heads-up! We've updated the docs to reflect the changes. It seems they only allow staging builds to reside on the repo for a limited period of time so we'll keep the docs updated as the beta progresses. Along with the newer repo, there is also an updated build in the dev branch that you may want to check out.
