### ISSUE TITLE
Could not find com.aerisweather:aeris-maps-lib:2.0.0_Beta2@aar

### ISSUE THREAD

**Issue by mhdjazmati** [aerisweather/AerisAndroidSDK#5]
hello :
i'm getting this error
Could not find com.aerisweather:aeris-maps-lib:2.0.0_Beta2@aar
i'm putting this in my build.gradle and it kept getting this .

please help

**Comment by sshie** [comment]
Hello,

Thanks for getting in touch - we verified that the repo is healthy and were able to link to it in a test app. Our Gradle looks like this:
```
...
repositories {
    mavenCentral()
    jcenter()
}
dependencies {
    compile ('com.aerisweather:aeris-maps-lib:2.0.0_Beta2@aar') {
        transitive true
    }
...
```
Can you provide the error that you're seeing?

**Comment by mhdjazmati** [comment]
hello , im sorry the problem was in my SDK , your repo is working just fine , thnx !!
