### ISSUE TITLE
Question: Any work on a React-Native wrapper?

### ISSUE THREAD

**Issue by wkw** [aerisweather/AerisAndroidSDK#6]
I'm about to start on a react native module for the aeris sdk, for one of your customers. Wanted to ask if you know of any work in this direction, or have explored it internally before I spend the time.

**Comment by sshie** [comment]
Hi Wayne,

Thanks for your question. Unfortunately, there are no plans for a React Native toolkit at this time. We are looking into adding a 3rd party libraries page though, so if you would like to share your work we would be happy to promote you and your completed module on our website.

Thanks!

**Comment by wkw** [comment]
Appreciate the fast response. Thank you. (all my interactions with Aeris have been great!)
Of course I'll pass back whatever I can in case it's useful to others. Your API is big, but we're only doing radar view. Nonetheless, it's the wrapper part that may be useful, and what I now have to work through.
Thank you again.

**Comment by sshie** [comment]
Sounds great, thanks!
