### ISSUE TITLE
beta 2 and API Docs during transition

### ISSUE THREAD

**Issue by wkw** [aerisweather/AerisAndroidSDK#7]
Couple questions. 
Working on new (React Native) integration and without thinking about it, I just went with Beta2. Am I safe in continuing work based on that SDK? I can avoid implementing for old, then very soon having to update to v2?

More urgent at the moment for me,  is whether I can presume the apidocs with hamweather package names are mostly the same except for changing the package name?  Or, are there apidocs for beta2 somewhere that I haven't found?

I'm familiar with this page https://www.aerisweather.com/support/docs/toolkits/aeris-android-sdk/reference/2.0.0-beta/

thanks!

**Comment by sshie** [comment]
Great questions! 

While we can't promise that there won't be a few changes with the final release of version 2.0, we're doing our best to make sure that the beta releases are as backward compatible as possible. That includes back to v1.2 of the SDK (with working but deprecated methods), and through the various betas as well. We use the SDK with our own projects, so we have a vested interest in making things as painless as we can... :-) 

Regarding the docs, there are updated javadocs in the beta repositories. Here's the link to the docs jar file:  [https://oss.sonatype.org/service/local/repositories/releases/content/com/aerisweather/aeris-core-lib/2.0.0_Beta2/aeris-core-lib-2.0.0_Beta2-javadoc.jar](https://oss.sonatype.org/service/local/repositories/releases/content/com/aerisweather/aeris-core-lib/2.0.0_Beta2/aeris-core-lib-2.0.0_Beta2-javadoc.jar).

Let us know if you need anything else.

**Comment by wkw** [comment]
@sshie perfect! Thanks. Didn't know to look there (first time Android developer at this point)

**Comment by sshie** [comment]
No problem at all!
