### ISSUE TITLE
How to animate radar

### ISSUE THREAD

**Issue by wkw** [aerisweather/AerisAndroidSDK#8]
(sorry to bug you folks so much, this probably won't be the last time...)

I have the demo app running... but I can't seem to locate in the app, the app's code or any of the docs how to animate the radar. I toyed with `options.setAnimationSpeed()` but no change, nor did I expect that to do much.

Is there some control that is supposed to display with a play/stop button? Or can there be? I'd welcome code snippets or some pointers.

Also any advice on showing a legend for the Radar is welcomed and probably needed before I put this to app to bed.

--

We have an iOS version of our app for which I took over maintenance of, and there is a slide-down legend at top of view, and some animation controls. I haven't dug too deeply into whether those were all being provided by the previous developer, or semi-freebies from Aeris SDK.  Image attached. I suspect client is looking for feature parity on the Android.

Many thanks!

![image](https://cloud.githubusercontent.com/assets/1691220/23230408/c9604868-f911-11e6-9fc1-26b063ce7f6a.png)

**Comment by sshie** [comment]
Hi Wayne,

Apologies for the delay responding here (I think we may have answered you via support?). The latest beta 3 now includes support for animating the AMP layers. Check out the updated docs and demo project for details.

**Comment by wkw** [comment]
Hehe, I thought maybe I had bugged you folks to the point of exhaustion!  Yes, I did end up getting a response through Support channel, which at that time was, "stick to the previous release". But thanks for the update. 
I was worried that the beta demo did have animation in it but for whatever reason it wasn't working / showing in my emulator. 
Sadly, I ran out of time for the project and had to downgrade to embedding JS api in it (React Native app). Animations aside, I couldn't figure out how to pull a fragment into RN's android view system in time I had.

**Comment by sshie** [comment]
Lol, no worries, we're here to to be bugged. :-)

That stinks that we didn't get a solution to you in time. If you get back around to an Android implementation, let us know. The full release of the SDK v2.0 will be out shortly and we're excited to see what folks can do with it!
